"""Initial migration

Revision ID: 6471a515da78
Revises: 
Create Date: 2026-02-09 18:02:30.459302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6471a515da78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_status', sa.Enum('PENDING', 'MATCHED', 'IGNORED', name='transactionstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('property',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('landlord_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('VACANT', 'OCCUPIED', 'MAINTENANCE', name='housestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_number'), 'house', ['number'], unique=True)
    op.create_index(op.f('ix_house_status'), 'house', ['status'], unique=False)
    op.create_table('tenant',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hse', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MOVING_OUT', 'VACATED', name='tenantstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hse'], ['house.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_email'), 'tenant', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_national_id'), 'tenant', ['national_id'], unique=True)
    op.create_index(op.f('ix_tenant_status'), 'tenant', ['status'], unique=False)
    op.create_table('invoice',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('hse_id', sa.Uuid(), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'UNPAID', name='invoicestatus'), nullable=False),
    sa.Column('date_of_gen', sa.DateTime(), nullable=False),
    sa.Column('date_due', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['hse_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_hse_id'), 'invoice', ['hse_id'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_index(op.f('ix_invoice_tenant_id'), 'invoice', ['tenant_id'], unique=False)
    op.create_table('maintenancebill',
    sa.Column('hse_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('parts_cost', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='maintenancestatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', name='maintenancepaymentstatus'), nullable=False),
    sa.Column('date_raised', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hse_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenancebill_hse_id'), 'maintenancebill', ['hse_id'], unique=False)
    op.create_index(op.f('ix_maintenancebill_tenant_id'), 'maintenancebill', ['tenant_id'], unique=False)
    op.create_table('payment',
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('maintenance_bill_id', sa.Uuid(), nullable=True),
    sa.Column('amount_expected', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('transaction_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIIED', name='paymentstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['maintenance_bill_id'], ['maintenancebill.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_maintenance_bill_id'), 'payment', ['maintenance_bill_id'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transaction_id'), 'payment', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_ref'), 'payment', ['transaction_ref'], unique=False)
    op.create_table('utilitybill',
    sa.Column('date_gen', sa.DateTime(), nullable=False),
    sa.Column('bill_type', sa.Enum('WATER', 'ELECTRICITY', 'OTHER', name='billtype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilitybill_invoice_id'), 'utilitybill', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilitybill_invoice_id'), table_name='utilitybill')
    op.drop_table('utilitybill')
    op.drop_index(op.f('ix_payment_transaction_ref'), table_name='payment')
    op.drop_index(op.f('ix_payment_transaction_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_maintenance_bill_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_maintenancebill_tenant_id'), table_name='maintenancebill')
    op.drop_index(op.f('ix_maintenancebill_hse_id'), table_name='maintenancebill')
    op.drop_table('maintenancebill')
    op.drop_index(op.f('ix_invoice_tenant_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_hse_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_tenant_status'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_national_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_email'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_house_status'), table_name='house')
    op.drop_index(op.f('ix_house_number'), table_name='house')
    op.drop_table('house')
    op.drop_table('property')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('role')
    # ### end Alembic commands ###
