"""adding payment date and reference id

Revision ID: 71c4890dee2b
Revises: e3f6c9a1b7d2
Create Date: 2026-07-14 16:54:47.382921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71c4890dee2b'
down_revision: Union[str, Sequence[str], None] = 'e3f6c9a1b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('date_paid', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('rent_allocated', sa.Float(), nullable=False))
    op.add_column('payment', sa.Column('utilities_allocated', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'utilities_allocated')
    op.drop_column('payment', 'rent_allocated')
    op.drop_column('payment', 'date_paid')
    # ### end Alembic commands ###
