"""Added Pivot Table for tenants & house

Revision ID: 7a0a04f884c3
Revises: f5e12a5ad423
Create Date: 2026-03-09 12:46:09.436280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a0a04f884c3'
down_revision: Union[str, Sequence[str], None] = 'f5e12a5ad423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_unit',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('hse_id', sa.Uuid(), nullable=False),
    sa.Column('rent_begin', sa.DateTime(), nullable=False),
    sa.Column('rent_end', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hse_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_unit_hse_id'), 'tenant_unit', ['hse_id'], unique=False)
    op.create_index(op.f('ix_tenant_unit_id'), 'tenant_unit', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_unit_tenant_id'), 'tenant_unit', ['tenant_id'], unique=False)
    op.add_column('invoice', sa.Column('tenant_unit_id', sa.Uuid(), nullable=False))
    op.add_column('invoice', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_invoice_hse_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_tenant_id'), table_name='invoice')
    op.drop_constraint(op.f('invoice_hse_id_fkey'), 'invoice', type_='foreignkey')
    op.drop_constraint(op.f('invoice_tenant_id_fkey'), 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'tenant_unit', ['tenant_unit_id'], ['id'])
    op.drop_column('invoice', 'hse_id')
    op.drop_column('invoice', 'tenant_id')
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('tenant_hse_fkey'), 'tenant', type_='foreignkey')
    op.drop_column('tenant', 'hse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('hse', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tenant_hse_fkey'), 'tenant', 'house', ['hse'], ['id'])
    op.drop_column('payment', 'updated_at')
    op.add_column('invoice', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('invoice', sa.Column('hse_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_tenant_id_fkey'), 'invoice', 'tenant', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('invoice_hse_id_fkey'), 'invoice', 'house', ['hse_id'], ['id'])
    op.create_index(op.f('ix_invoice_tenant_id'), 'invoice', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoice_hse_id'), 'invoice', ['hse_id'], unique=False)
    op.drop_column('invoice', 'updated_at')
    op.drop_column('invoice', 'tenant_unit_id')
    op.drop_index(op.f('ix_tenant_unit_tenant_id'), table_name='tenant_unit')
    op.drop_index(op.f('ix_tenant_unit_id'), table_name='tenant_unit')
    op.drop_index(op.f('ix_tenant_unit_hse_id'), table_name='tenant_unit')
    op.drop_table('tenant_unit')
    # ### end Alembic commands ###
