"""delinked tenants and maintenance bill

Revision ID: 94fe910abb94
Revises: a6898444860e
Create Date: 2026-02-21 11:33:09.352111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94fe910abb94'
down_revision: Union[str, Sequence[str], None] = 'a6898444860e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenancebill_tenant_id'), table_name='maintenancebill')
    op.drop_constraint(op.f('maintenancebill_tenant_id_fkey'), 'maintenancebill', type_='foreignkey')
    op.drop_column('maintenancebill', 'payment_status')
    op.drop_column('maintenancebill', 'tenant_id')
    op.drop_index(op.f('ix_payment_maintenance_bill_id'), table_name='payment')
    op.drop_constraint(op.f('payment_maintenance_bill_id_fkey'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'maintenance_bill_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('maintenance_bill_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payment_maintenance_bill_id_fkey'), 'payment', 'maintenancebill', ['maintenance_bill_id'], ['id'])
    op.create_index(op.f('ix_payment_maintenance_bill_id'), 'payment', ['maintenance_bill_id'], unique=False)
    op.add_column('maintenancebill', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('maintenancebill', sa.Column('payment_status', postgresql.ENUM('PAID', 'UNPAID', name='maintenancepaymentstatus'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('maintenancebill_tenant_id_fkey'), 'maintenancebill', 'tenant', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_maintenancebill_tenant_id'), 'maintenancebill', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
