"""Made the house number not unique

Revision ID: a5997a46cd22
Revises: c64633b46176
Create Date: 2026-03-29 13:28:10.933122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5997a46cd22'
down_revision: Union[str, Sequence[str], None] = 'c64633b46176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_number'), table_name='house')
    op.create_index(op.f('ix_house_number'), 'house', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_number'), table_name='house')
    op.create_index(op.f('ix_house_number'), 'house', ['number'], unique=True)
    # ### end Alembic commands ###
