"""Added cascade delete between invoices and utilities fixed

Revision ID: b54358515aa1
Revises: f15e4b0b26cb
Create Date: 2026-03-18 15:44:20.796833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b54358515aa1'
down_revision: Union[str, Sequence[str], None] = 'f15e4b0b26cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('utilitybill_invoice_id_fkey'), 'utilitybill', type_='foreignkey')
    op.create_foreign_key(None, 'utilitybill', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilitybill', type_='foreignkey')
    op.create_foreign_key(op.f('utilitybill_invoice_id_fkey'), 'utilitybill', 'invoice', ['invoice_id'], ['id'])
    # ### end Alembic commands ###
