"""Made roles field optional

Revision ID: ba904fe3deb1
Revises: 6471a515da78
Create Date: 2026-02-09 18:16:53.464733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba904fe3deb1'
down_revision: Union[str, Sequence[str], None] = '6471a515da78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('role', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('role', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('role', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###
