"""Changed payment model

Revision ID: d360ba2199c2
Revises: 94fe910abb94
Create Date: 2026-02-21 12:04:24.577883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd360ba2199c2'
down_revision: Union[str, Sequence[str], None] = '94fe910abb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payment_tenant_id'), 'payment', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'payment', 'tenant', ['tenant_id'], ['id'])
    op.drop_column('payment', 'amount_expected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('amount_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_index(op.f('ix_payment_tenant_id'), table_name='payment')
    op.drop_column('payment', 'tenant_id')
    # ### end Alembic commands ###
