"""Made the national id field nullable for bulk upload

Revision ID: dbe89a58f239
Revises: 2dcdc6a23fb7
Create Date: 2026-03-17 17:19:16.867756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbe89a58f239'
down_revision: Union[str, Sequence[str], None] = '2dcdc6a23fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
