"""Added cascade delete between invoices and utilities fix

Revision ID: f15e4b0b26cb
Revises: 4af233bc4609
Create Date: 2026-03-18 15:40:15.177695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f15e4b0b26cb'
down_revision: Union[str, Sequence[str], None] = '4af233bc4609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
